name: 'Delete Deployment Environment'
description: 'Delete the entire environment and deployments for the branch the action is running on'
author: "strumwolf"
branding:
  icon: briefcase
  color: gray-dark
inputs:
  token:
    description: GitHub access token
    required: true
  environment:
    description: Environment to be deleted
    required: true
  owner:
    description: Owner name
    required: false
  repo:
    description: repo name
    required: false
  onlyRemoveDeployments:
    description: Only remove deployments, keep the environment. Defaults to false
    required: false
  onlyDeactivateDeployments:
    description: Only inactive deployments, keep the environment and deployments. Defaults to false
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
